run:
  modules-download-mode: readonly
linters:
  enable-all: true
  disable:
    # Deprecated
    - execinquery
    - gomnd

    # Purposely disabled
    - wsl
    - nlreturn
    - godox
    - dupword

    # TODO:
    - testpackage
    - intrange
    - ireturn
    - errorlint
    - err113
    - forcetypeassert
    - errcheck
    - exhaustive
    - funlen
    - gocognit
    - cyclop

linters-settings:
  errcheck:
    check-blank: true
  whitespace:
    multi-if: false
    multi-func: false
  govet:
    shadow: true
  varnamelen:
    ignore-decls:
      - v Value
      - i int

issues:
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - revive
        - goconst
