run:
  modules-download-mode: readonly
linters:
  enable-all: true
  disable:
    # Deprecated
    - execinquery
    - gomnd
    - exportloopref

    # Purposely disabled
    - wsl
    - nlreturn
    - godox
    - dupword
    - depguard
    - ireturn

    # False positives
    - exhaustive

linters-settings:
  errcheck:
    check-blank: true
  whitespace:
    multi-if: false
    multi-func: false
  govet:
    shadow: true
  varnamelen:
    ignore-decls:
      - v Value
      - i int
      - g G

issues:
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - revive
        - goconst
        - funlen
        - cyclop
        - gocognit
        - err113
