run:
  modules-download-mode: readonly
linters:
  enable-all: true
  disable:
    # Deprecated
    - execinquery
    - gomnd

    # Purposely disabled
    - wsl
    - nlreturn
    - godox

    # TODO:
    - paralleltest
    - varnamelen
    - testpackage
    - intrange
    - ireturn
    - mnd
    - errorlint
    - err113
    - goconst
    - gochecknoinits
    - forcetypeassert
    - exhaustruct
    - errcheck
    - exhaustive
    - errname
    - gocritic
    - funlen
    - gocognit
    - revive
    - cyclop
    - gochecknoglobals
    - inamedparam
    - wrapcheck
    - dupword
    - perfsprint

linters-settings:
  errcheck:
    check-blank: true
  whitespace:
    multi-if: false
    multi-func: false
  govet:
    shadow: true
  varnamelen:
    ignore-decls: []

issues:
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - revive
        - wrapcheck
